- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Wait up to 300 seconds (5m) for EC2 bootstrap
      wait_for_connection:
        timeout: 300
    - name: Gather facts
      setup:
  
  roles:
    - geerlingguy.jenkins
  vars:
    jenkins_repo_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    jenkins_repo_key_url: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key